Mirroring with license   * Correction to list file CANCEL switch behaviour   * Removed printing of selected topic list indexes   * Added README in English   * Fixed License file   * Preparation for .deb package building

diff --git a/rosbag_visual_topic_filter b/rosbag_visual_topic_filter
--- a/rosbag_visual_topic_filter
+++ b/rosbag_visual_topic_filter
@@ -76,7 +76,7 @@ NEW_FILTERED_BAG_NAME=`whiptail --title  "File name for filtered output" --input
 errorcode=$?
 if [[ -z "${NEW_FILTERED_BAG_NAME}" || "${NEW_FILTERED_BAG_NAME}" == "${SELECTED_BAG_NAME}" ]]
 then
-     echo -e "ERROR: uncorrect output file name! Abort"
+     echo -e "ERROR: incorrect output file name or user cancelled operation. Abort"
      cd "${RUN_DIR}"
      exit 1
 else
@@ -174,28 +174,30 @@ fi
 
 selected_topic_list=(${selected_topics})
 
-echo -e "${selected_topic_list[@]}"
-
 whiptail --yesno --defaultno --title "Topic list preservation" "Do you want to save the list of selected topics" 0 0 3>&1 1>&2 2>&3
 save_topic_list=$?
 if [[ ${save_topic_list} -eq 0 ]]
 then
     NEW_TOPIC_LIST_FILE=`whiptail --title  "File name for topic list" --inputbox  "Please enter filename for topic list" 10 60 "${TOPIC_LIST_FILE}" 3>&1 1>&2 2>&3`
-    errorcode=$?
-    if [[ -z "${NEW_TOPIC_LIST_FILE}" || "${NEW_TOPIC_LIST_FILE}" == "${TOPIC_LIST_FILE}" ]]
+    if [[ $? -eq 0 ]]
     then
-        echo -e "WARNING: wrong filename for topic list to save. Saving to default ${TOPIC_LIST_FILE}"
+        if [[ -z "${NEW_TOPIC_LIST_FILE}" || "${NEW_TOPIC_LIST_FILE}" == "${TOPIC_LIST_FILE}" ]]
+        then
+            echo -e "WARNING: wrong filename for topic list to save. Saving to default ${TOPIC_LIST_FILE}"
+        else
+            TOPIC_LIST_FILE="${NEW_TOPIC_LIST_FILE}"
+        fi
+        if [[ -f "${TOPIC_LIST_FILE}" ]]
+        then
+            rm -rvf "${TOPIC_LIST_FILE}"
+        fi
+        for ((i=0; i < "${#selected_topic_list[@]}"; i++))
+        do
+            echo -e "${result_topic_list[ ${selected_topic_list[i]} ]}" >> "${TOPIC_LIST_FILE}"
+        done
     else
-        TOPIC_LIST_FILE="${NEW_TOPIC_LIST_FILE}"
+        echo -e "Topic list preservation cancelled"
     fi
-    if [[ -f "${TOPIC_LIST_FILE}" ]]
-    then
-        rm -rvf "${TOPIC_LIST_FILE}"
-    fi
-    for ((i=0; i < "${#selected_topic_list[@]}"; i++))
-    do
-        echo -e "${result_topic_list[ ${selected_topic_list[i]} ]}" >> "${TOPIC_LIST_FILE}"
-    done
 fi
 
 filter_string=""
